name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libssl-dev
      - name: Build
        run: cargo build --all --release
      - name: Run unit tests
        run: cargo test --all --release --lib
      - name: Run integration tests
        run: cargo test --all --release --tests
      - name: Run transport integration tests
        run: cargo test --test integration_transports --release || true
      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: target/debug/build/gsheets_mcp-*/out/*.log
